-- ============================================================
-- INSURE dbt Layer 1: STAGING
-- 원본 테이블 정규화 뷰 (GRANDATA + 공공데이터)
-- ============================================================

USE DATABASE INSURE_DB;
USE SCHEMA STAGING;

-- ─────────────────────────────────────────────
-- STG_ASSET_INCOME: GRANDATA.ASSET_INCOME_INFO 정규화
-- 핵심 팩트 테이블 - 115개 컬럼 중 INSURE 관련 40+개 선별
-- ─────────────────────────────────────────────
CREATE OR REPLACE VIEW STG_ASSET_INCOME AS
SELECT
    -- 키
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH                          AS YEAR_MONTH,
    GENDER,
    AGE_GROUP,
    -- 인구
    CUSTOMER_COUNT,
    -- 소득 분포 (7개 구간)
    MEDIAN_INCOME,
    RATE_INCOME_UNDER_10M,
    RATE_INCOME_10M_TO_20M,
    RATE_INCOME_20M_TO_30M,
    RATE_INCOME_30M_TO_40M,
    RATE_INCOME_40M_TO_50M,
    RATE_INCOME_50M_TO_70M,
    RATE_INCOME_OVER_70M,
    -- 직업 분포 (7개 그룹)
    RATE_MODEL_GROUP_LARGE_COMPANY_EMPLOYEE,
    RATE_MODEL_GROUP_GENERAL_EMPLOYEE,
    RATE_MODEL_GROUP_PROFESSIONAL,
    RATE_MODEL_GROUP_FIELD_WORK,
    RATE_MODEL_GROUP_SME,
    RATE_MODEL_GROUP_OTHERS,
    -- 신용 점수
    AVERAGE_SCORE                                AS CREDIT_SCORE_AVG,
    RATE_SCORE1                                  AS CREDIT_HIGH_RATE,
    RATE_SCORE2                                  AS CREDIT_MID_RATE,
    RATE_SCORE3                                  AS CREDIT_LOW_RATE,
    -- 연체 정보
    DELINQUENT_1D_COUNT,
    DELINQUENT_90_COUNT,
    AVERAGE_DELINQUENT_AMOUNT,
    -- 자산/주택
    AVERAGE_ASSET_AMOUNT,
    OWN_HOUSING_COUNT,
    MULTIPLE_HOUSING_COUNT,
    -- 주거 규모
    PYEONG_UNDER_20_COUNT                        AS SMALL_UNIT_COUNT,
    PYEONG_20_TO_40_COUNT                        AS MID_UNIT_COUNT,
    PYEONG_40_TO_60_COUNT                        AS LARGE_UNIT_COUNT,
    PYEONG_OVER_60_COUNT                         AS LUXURY_UNIT_COUNT,
    -- 대출
    BALANCE_COUNT,
    MORTGAGE1_BALANCE_COUNT,
    MORTGAGE2_BALANCE_COUNT,
    HOUSING_BALANCE_COUNT,
    -- 카드 사용
    TOTAL_USAGE_AMOUNT,
    AVERAGE_FULL_PAYMENT_USAGE_AMOUNT            AS FULL_PAY_AMOUNT,
    AVERAGE_INSTALLMENT_USAGE_AMOUNT             AS INSTALLMENT_AMOUNT,
    AVERAGE_ABROAD_AMOUNT                        AS ABROAD_SPEND_AMOUNT,
    -- 고소득
    RATE_HIGH_END
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.ASSET_INCOME_INFO;

-- ─────────────────────────────────────────────
-- STG_CARD_SALES: 카드 매출 정규화
-- ─────────────────────────────────────────────
CREATE OR REPLACE VIEW STG_CARD_SALES AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH                          AS YEAR_MONTH,
    GENDER,
    AGE_GROUP,
    BUSINESS_TYPE,
    TOTAL_USAGE_AMOUNT,
    TOTAL_USAGE_COUNT,
    AVERAGE_USAGE_AMOUNT
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.CARD_SALES_INFO;

-- ─────────────────────────────────────────────
-- STG_FLOATING_POP: 유동인구 정규화
-- ─────────────────────────────────────────────
CREATE OR REPLACE VIEW STG_FLOATING_POP AS
SELECT
    DISTRICT_CODE,
    STANDARD_YEAR_MONTH                          AS YEAR_MONTH,
    WEEKDAY_WEEKEND,
    GENDER,
    AGE_GROUP,
    TIME_SLOT,
    RESIDENTIAL_POPULATION,
    WORKING_POPULATION,
    VISITING_POPULATION,
    RESIDENTIAL_POPULATION + WORKING_POPULATION + VISITING_POPULATION AS TOTAL_POPULATION
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.FLOATING_POPULATION_INFO;

-- ─────────────────────────────────────────────
-- STG_DISTRICT_MASTER: 지역코드 마스터
-- ─────────────────────────────────────────────
CREATE OR REPLACE VIEW STG_DISTRICT_MASTER AS
SELECT
    *
FROM SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.M_SCCO_MST;

-- ─────────────────────────────────────────────
-- STG_APT_PRICE: 아파트 시세 (RICHGO)
-- ─────────────────────────────────────────────
CREATE OR REPLACE VIEW STG_APT_PRICE AS
SELECT
    BJD_CODE,
    SD,
    SGG,
    EMD,
    TOTAL_HOUSEHOLDS,
    YYYYMMDD,
    LEFT(YYYYMMDD::VARCHAR, 6)                   AS YEAR_MONTH,
    MEME_PRICE_PER_SUPPLY_PYEONG                 AS SALE_PRICE_PER_PYEONG,
    JEONSE_PRICE_PER_SUPPLY_PYEONG               AS JEONSE_PRICE_PER_PYEONG
FROM KOREAN_POPULATION__APARTMENT_MARKET_PRICE_DATA.HACKATHON_2025Q2.REGION_APT_RICHGO_MARKET_PRICE_M_H;

-- ─────────────────────────────────────────────
-- STG_공공데이터 뷰들 (RAW_PUBLIC → STAGING)
-- ─────────────────────────────────────────────
CREATE OR REPLACE VIEW STG_FIRE_STATS AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.FIRE_STATS;

CREATE OR REPLACE VIEW STG_CRIME_STATS AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.CRIME_STATS;

CREATE OR REPLACE VIEW STG_BUILDING_AGE AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.BUILDING_AGE;

CREATE OR REPLACE VIEW STG_WEATHER_RISK AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.WEATHER_RISK;

CREATE OR REPLACE VIEW STG_SINGLE_HOUSEHOLD AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.SINGLE_HOUSEHOLD;

CREATE OR REPLACE VIEW STG_CCTV AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.CCTV_INSTALLATION;

CREATE OR REPLACE VIEW STG_REAL_ESTATE AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.REAL_ESTATE_TRANSACTIONS;

CREATE OR REPLACE VIEW STG_FIRE_FACILITY AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.FIRE_FACILITY;

CREATE OR REPLACE VIEW STG_CONSUMER_ACCIDENT AS
SELECT * FROM INSURE_DB.RAW_PUBLIC.CONSUMER_ACCIDENT;

SELECT 'STAGING layer: 13 views created' AS status;
