-- ============================================================
-- INSURE: Permission Grants for MCP_ROLE
-- Allows Streamlit app to access all required schemas/tables
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Database & Schema access
GRANT USAGE ON DATABASE INSURE_DB TO ROLE MCP_ROLE;
GRANT USAGE ON SCHEMA INSURE_DB.ANALYTICS TO ROLE MCP_ROLE;
GRANT USAGE ON SCHEMA INSURE_DB.MART TO ROLE MCP_ROLE;
GRANT USAGE ON SCHEMA INSURE_DB.STAGING TO ROLE MCP_ROLE;
GRANT USAGE ON SCHEMA INSURE_DB.INTERMEDIATE TO ROLE MCP_ROLE;

-- Streamlit app access
GRANT USAGE ON STREAMLIT INSURE_DB.ANALYTICS.INSURE_DASHBOARD TO ROLE MCP_ROLE;
GRANT READ ON STAGE INSURE_DB.ANALYTICS.STS_STREAMLIT TO ROLE MCP_ROLE;

-- Warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MCP_ROLE;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE MCP_ROLE;
GRANT MONITOR ON WAREHOUSE COMPUTE_WH TO ROLE MCP_ROLE;

-- Table/View SELECT permissions
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE_DB.MART TO ROLE MCP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA INSURE_DB.MART TO ROLE MCP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE_DB.STAGING TO ROLE MCP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA INSURE_DB.STAGING TO ROLE MCP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE_DB.INTERMEDIATE TO ROLE MCP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA INSURE_DB.INTERMEDIATE TO ROLE MCP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURE_DB.ANALYTICS TO ROLE MCP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA INSURE_DB.ANALYTICS TO ROLE MCP_ROLE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA INSURE_DB.ANALYTICS TO ROLE MCP_ROLE;

-- Set default role
ALTER USER CROWNPANTO SET DEFAULT_ROLE = 'ACCOUNTADMIN';
ALTER WAREHOUSE COMPUTE_WH RESUME IF SUSPENDED;

SELECT 'All grants applied' AS status;
