[theme]
base                     = "light"
backgroundColor          = "#dde3ec"
secondaryBackgroundColor = "#cdd5e0"
textColor                = "#0f172a"
primaryColor             = "#818cf8"
font                     = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
